### ISSUE TITLE
Вопрос по LaTeX.

### ISSUE THREAD

**Issue by ghost** [EliseyP/csl_odt2tex#1]
Здравствуйте, можно ли удобно использовать этот набор утилит для верстки текстов непосредственно в LaTeX (без конвертации из ODF?). Меня интересует набор Часослова в LaTeX, поэтому пытаюсь найти примеры сложных текстов и переработать для своих нужд.

**Comment by EliseyP** [comment]
Здравствуйте! Да, конечно, ODT в данном случае используется главным из-за удобства совместной работы с теми, кто не знаком с LaTeX. Также удобно "заливать" стилями абзацы (тоже организуемо для других редакторов).   
В LaTeX редакторе все можно верстать напрямую, единственное, что можно было бы посоветовать - организовать "сниппеты" для своего TeX-редактора.   
По поводу Часослова - есть как минимум Unicode-текст, например [здесь](https://www.ponomar.net/cgi-bin/bookreader2.cgi?uuid=79a74ae2-cec9-11e0-bc18-c69954a6a287). Я посмотрю, м.б. можно быстро его обработать.

**Comment by EliseyP** [comment]
Посмотрите, для примера, [Полунощница](https://github.com/EliseyP/csl_odt2tex/blob/main/%D0%9F%D0%BE%D0%BB%D1%83%D0%BD%D0%BE%D1%89%D0%BD%D0%B8%D1%86%D0%B0.tex), как часть Часослова.   
Правда я все же по-скору обрабатывал через ODT, по привычке.

**Comment by ghost** [comment]
Спасибо за помощь и за эту программу. Остановился на варианте обработки ODT файлов с ресура, которого вы указали и ручной правкой некоторых мест в LaTeX. Но почему-то не получается конвертировать (через csl2tex.py) [последование изобразительных](https://www.ponomar.net/cgi-bin/bookreader2.cgi?uuid=79a74ae2-cec9-11e0-bc18-c69954a6a287&file=06izobrazit.xml). Видимо форматирование/стиль ODT файла неверный?

```

~/Часослов $ python3 csl2tex.py -p Изобразительны.odt
Convert /home/rx/Часослов/Изобразительны.odt

Traceback (most recent call last):
  File "/home/rx/Часослов/csl2tex.py", line 447, in <module>
    main()
  File "/home/rx/Часослов/csl2tex.py", line 428, in main
    _init_tex = make_tex_init(_file)
  File "/home/rx/Часослов/csl2tex.py", line 356, in make_tex_init
    csl_odt2tex(
  File "/home/rx/Часослов/CslOdt2Tex.py", line 156, in csl_odt2tex
    title = get_odt_title(odt_path)
  File "/home/rx/Часослов/CslOdt2Tex.py", line 45, in get_odt_title
    raise er
  File "/home/rx/Часослов/CslOdt2Tex.py", line 43, in get_odt_title
    odt_obj = Odt(_odt_path)
  File "/home/rx/Часослов/ProcessOdtByXML.py", line 143, in __init__
    self.styles_handle()
  File "/home/rx/Часослов/ProcessOdtByXML.py", line 534, in styles_handle
    _style_name = _st.attributes.get((_ns_style, 'name'))

AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by EliseyP** [comment]
Здравствуйте. Скрипт `csl2tex.py` предназначен для odt-файлов, в которых текст оформлен стилями из шаблонов [Гимнография 20 новый.ott](https://github.com/EliseyP/csl_odt2tex/blob/main/%D0%93%D0%B8%D0%BC%D0%BD%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F%2020%20%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9.ott).  
В Вашем примере файл `Изобразительны.odt` каким-то образом был обработан после скачивания с сайта?  
Если нет, то простейшим вариантом может быть следущее:  

- Открыть файл в LibreOffice.  
- Выделить весь текст.
- Применить к выделенному тексту стиль `Основной текст` (например, через `Ctrl+0`).  
- Загрузить стили из шаблона [Гимнография 20 новый.ott](https://github.com/EliseyP/csl_odt2tex/blob/main/%D0%93%D0%B8%D0%BC%D0%BD%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F%2020%20%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9.ott) (`Меню|Стили|Загрузить стили из шаблона`).  
- Сохранить файл.

Теперь его можно конвертировать в TeX. Каждый абзац будет обрамлен макросом \Txt{}.  
В этом архиве [06izobrazit.zip](https://github.com/EliseyP/csl_odt2tex/files/9147964/06izobrazit.zip) - обработанный таким образом odt-файл и результат конвертации (tex и pdf).  
Соответственно, если нужны заголовки и прочее, то нужно дальнейшее оформление стилями и повторная конвертация.

**Comment by EliseyP** [comment]
UPD: поправил скрипт, теперь он обрабатывает odt-файл без предварительной обработки.
